# Vlaid types
VALID_TYPES="laptop tablet smartphone"

# Max items per location
MAX_ITEMS_PER_LOCATION=10

# Locations
ALLOWED_LOCATIONS_laptop=RACK_A
ALLOWED_LOCATIONS_tablet=RACK_B
ALLOWED_LOCATIONS_smartphone=RACK_C

# Paths
LOG_FILE="../logs/system.log"
SCRIPT_DIR="../scripts"
LOG_LEVEL="INFO"
