DROP TABLE order_items;
DROP TABLE orders;   
DROP TABLE inventory;     
DROP TABLE locations;     
DROP TABLE customers;  
DROP TABLE products;
DROP TABLE valid_location_mappings;
DROP TABLE valid_product_types;


CREATE TABLE valid_product_types (
    product_type NVARCHAR2(50) PRIMARY KEY,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE valid_location_mappings (
    valid_location_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    product_type NVARCHAR2(50),
    allowed_location NVARCHAR2(20),
    is_active CHAR(1) DEFAULT 'Y',
    FOREIGN key (product_type) references valid_product_types(product_type)
);

create table products (
    product_id nvarchar2(20) primary key,
    name nvarchar2(255),
    product_type nvarchar2(50),
    quantity int,
    receive_date date DEFAULT sysdate
);

create table locations (
    location_id nvarchar2(20) primary key,
    max_capacity int,
    current_count int default 0
);

create table inventory (
    inventory_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    product_id nvarchar2(20) unique not NULL,
    product_type nvarchar2(50),
    location_id nvarchar2(20),
    quantity_number int,
    foreign key (product_id) references products(product_id),
    foreign key (location_id) references locations(location_id)
);

create table customers (
    customer_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    customer_fname nvarchar2(80),
    customer_lname nvarchar2(80),
    address nvarchar2(40)
);

create table orders (
    order_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    customer_id int,
    status nvarchar2(20),
    ordered_at DATE DEFAULT sysdate
);

create table order_items (
    order_item_id int GENERATED BY DEFAULT AS IDENTITY primary key,
    order_id int,
    product_id nvarchar2(20),
    quantity int,
    foreign key (product_id) references inventory(product_id),
    foreign key (order_id) references orders(order_id)
);

INSERT INTO locations (location_id, max_capacity, current_count)
VALUES ('RACK_A', 10, 0);
 
INSERT INTO locations (location_id, max_capacity, current_count)
VALUES ('RACK_B', 10, 0);
 
INSERT INTO locations (location_id, max_capacity, current_count)
VALUES ('RACK_C', 10, 0);
 
COMMIT;

INSERT INTO customers (customer_fname, customer_lname, address)
VALUES ('John', 'Doe', 'Athens');
 
INSERT INTO customers (customer_fname, customer_lname, address)
VALUES ('Maria', 'Smith', 'Thessaloniki');
 
-- INSERT INTO customers (customer_fname, customer_lname, address)
-- VALUES ('Γιάννης', 'Παπαδόπουλος', 'Αθήνα, Οδός Ελευθερίας 10');
 
-- INSERT INTO customers (customer_fname, customer_lname, address)
-- VALUES ('Μαρία', 'Βλαχοπούλου', 'Θεσσαλονίκη, Αριστοτέλους 5');
 
-- INSERT INTO customers (customer_fname, customer_lname, address)
-- VALUES ('Νίκος', 'Ανδρέου', 'Πάτρα, Κορίνθου 20');
 
COMMIT;

CREATE OR REPLACE FUNCTION check_stock (
    p_product_id IN VARCHAR2,
    p_quantity   IN NUMBER
) RETURN NUMBER
IS
    v_stock NUMBER;
BEGIN
    SELECT NVL(SUM(quantity_number), 0)
    INTO v_stock
    FROM inventory
    WHERE product_id = p_product_id;

    IF v_stock >= p_quantity THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;
/


CREATE OR REPLACE PROCEDURE process_order_proc (
    p_order_id IN NUMBER
) AS

    CURSOR order_cursor IS
        SELECT product_id, quantity
        FROM order_items
        WHERE order_id = p_order_id;

    v_stock NUMBER;
    v_success NUMBER := 1;

BEGIN

    -- loop through order items
    FOR rec IN order_cursor LOOP

        -- check stock
        SELECT NVL(SUM(quantity_number), 0)
        INTO v_stock
        FROM inventory
        WHERE product_id = rec.product_id;

        IF v_stock < rec.quantity THEN
            v_success := 0;
            DBMS_OUTPUT.PUT_LINE('Insufficient stock for ' || rec.product_id);
        END IF;

    END LOOP;

    -- if any failed → mark order failed
    IF v_success = 0 THEN
        UPDATE orders
        SET status = 'FAILED'
        WHERE order_id = p_order_id;

        COMMIT;
        RETURN;
    END IF;

    -- otherwise process order
    FOR rec IN order_cursor LOOP

        UPDATE inventory
        SET quantity_number = quantity_number - rec.quantity
        WHERE product_id = rec.product_id;

    END LOOP;

    UPDATE orders
    SET status = 'SHIPPED'
    WHERE order_id = p_order_id;

    COMMIT;

    DBMS_OUTPUT.PUT_LINE('Order processed successfully');

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Order not found');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/


CREATE OR REPLACE TRIGGER update_location_count
AFTER INSERT OR UPDATE OR DELETE ON inventory
DECLARE
    v_location_id locations.location_id%TYPE;
BEGIN
    -- Βρες όλα τα distinct location_id που άλλαξαν
    FOR rec IN (SELECT DISTINCT location_id FROM inventory) LOOP
        UPDATE locations
        SET current_count = (
            SELECT NVL(SUM(quantity_number), 0)
            FROM inventory
            WHERE location_id = rec.location_id
        )
        WHERE location_id = rec.location_id;
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE sync_product_types(
    p_type_list VARCHAR2
) AS
    v_start NUMBER := 1;
    v_end NUMBER;
    v_type VARCHAR2(50);
BEGIN
    -- 1. Απενεργοποίησε όλους πρώτα
    UPDATE valid_product_types SET is_active = 'N';
    
    -- 2. Επεξεργασία λίστας: ενεργοποίησε όσους υπάρχουν, πρόσθεσε όσους λείπουν
    LOOP
        v_end := INSTR(p_type_list, ',', v_start);
        IF v_end = 0 THEN
            v_type := TRIM(SUBSTR(p_type_list, v_start));
            IF v_type IS NOT NULL THEN
                MERGE INTO valid_product_types dest
                USING (SELECT v_type AS product_type FROM dual) src
                ON (dest.product_type = src.product_type)
                WHEN MATCHED THEN UPDATE SET is_active = 'Y'
                WHEN NOT MATCHED THEN INSERT (product_type, is_active) VALUES (v_type, 'Y');
            END IF;
            EXIT;
        ELSE
            v_type := TRIM(SUBSTR(p_type_list, v_start, v_end - v_start));
            IF v_type IS NOT NULL THEN
                MERGE INTO valid_product_types dest
                USING (SELECT v_type AS product_type FROM dual) src
                ON (dest.product_type = src.product_type)
                WHEN MATCHED THEN UPDATE SET is_active = 'Y'
                WHEN NOT MATCHED THEN INSERT (product_type, is_active) VALUES (v_type, 'Y');
            END IF;
            v_start := v_end + 1;
        END IF;
    END LOOP;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✅ Product types synced');
END;
/

CREATE OR REPLACE TRIGGER trg_check_product_type
BEFORE INSERT OR UPDATE ON products
FOR EACH ROW
DECLARE
    v_active CHAR(1);
BEGIN
    SELECT is_active INTO v_active
    FROM valid_product_types
    WHERE product_type = :NEW.product_type;
    
    IF v_active = 'N' THEN
        RAISE_APPLICATION_ERROR(-20001, 'Product type ' || :NEW.product_type || ' is not allowed in current config');
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'Product type ' || :NEW.product_type || ' not found');
END;
/

CREATE OR REPLACE TRIGGER trg_check_location
BEFORE INSERT OR UPDATE ON inventory
FOR EACH ROW
DECLARE
    v_allowed VARCHAR2(20);
    v_active CHAR(1);
BEGIN
    -- Βρες το επιτρεπόμενο location για αυτόν τον τύπο
    SELECT allowed_location, is_active INTO v_allowed, v_active
    FROM valid_location_mappings
    WHERE product_type = :NEW.product_type;
    
    -- Έλεγξε αν ο τύπος είναι ενεργός
    IF v_active = 'N' THEN
        RAISE_APPLICATION_ERROR(-20003, 'Product type ' || :NEW.product_type || ' is not active');
    END IF;
    
    -- Έλεγξε αν το location είναι σωστό
    IF :NEW.location_id != v_allowed THEN
        RAISE_APPLICATION_ERROR(-20004, 'Product type ' || :NEW.product_type || 
                               ' must be stored in ' || v_allowed || ', not ' || :NEW.location_id);
    END IF;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20005, 'No location mapping found for product type: ' || :NEW.product_type);
END;
/
CREATE OR REPLACE PROCEDURE sync_location_config(
    p_mappings VARCHAR2  -- 'laptop:RACK_A,tablet:RACK_B,smartphone:RACK_C'
) AS
    v_start NUMBER := 1;
    v_end NUMBER;
    v_pair VARCHAR2(100);
    v_product_type VARCHAR2(50);
    v_location VARCHAR2(20);
    v_exists NUMBER;
BEGIN
    -- 1. Απενεργοποίησε όλες τις υπάρχουσες αντιστοιχίσεις
    UPDATE valid_location_mappings SET is_active = 'N';
    
    -- 2. Δημιουργία/ενεργοποίηση locations και mappings
    LOOP
        v_end := INSTR(p_mappings, ',', v_start);
        IF v_end = 0 THEN
            v_pair := TRIM(SUBSTR(p_mappings, v_start));
            IF v_pair IS NOT NULL THEN
                v_product_type := TRIM(SUBSTR(v_pair, 1, INSTR(v_pair, ':') - 1));
                v_location := TRIM(SUBSTR(v_pair, INSTR(v_pair, ':') + 1));
                
                -- 2α. Δημιουργία location αν δεν υπάρχει (με default capacity 50)
                SELECT COUNT(*) INTO v_exists FROM locations WHERE location_id = v_location;
                IF v_exists = 0 THEN
                    INSERT INTO locations (location_id, max_capacity, current_count) 
                    VALUES (v_location, 50, 0);
                END IF;
                
                -- 2β. Έλεγχος αν υπάρχει το product_type στο valid_product_types
                SELECT COUNT(*) INTO v_exists 
                FROM valid_product_types 
                WHERE product_type = v_product_type;
                
                IF v_exists > 0 THEN
                    MERGE INTO valid_location_mappings dest
                    USING (SELECT v_product_type AS pt, v_location AS loc FROM dual) src
                    ON (dest.product_type = src.pt)
                    WHEN MATCHED THEN UPDATE SET allowed_location = src.loc, is_active = 'Y'
                    WHEN NOT MATCHED THEN INSERT (product_type, allowed_location, is_active) 
                           VALUES (src.pt, src.loc, 'Y');
                END IF;
            END IF;
            EXIT;
        ELSE
            v_pair := TRIM(SUBSTR(p_mappings, v_start, v_end - v_start));
            IF v_pair IS NOT NULL THEN
                v_product_type := TRIM(SUBSTR(v_pair, 1, INSTR(v_pair, ':') - 1));
                v_location := TRIM(SUBSTR(v_pair, INSTR(v_pair, ':') + 1));
                
                -- Δημιουργία location αν δεν υπάρχει
                SELECT COUNT(*) INTO v_exists FROM locations WHERE location_id = v_location;
                IF v_exists = 0 THEN
                    INSERT INTO locations (location_id, max_capacity, current_count) 
                    VALUES (v_location, 50, 0);
                END IF;
                
                -- Έλεγχος ύπαρξης product_type
                SELECT COUNT(*) INTO v_exists 
                FROM valid_product_types 
                WHERE product_type = v_product_type;
                
                IF v_exists > 0 THEN
                    MERGE INTO valid_location_mappings dest
                    USING (SELECT v_product_type AS pt, v_location AS loc FROM dual) src
                    ON (dest.product_type = src.pt)
                    WHEN MATCHED THEN UPDATE SET allowed_location = src.loc, is_active = 'Y'
                    WHEN NOT MATCHED THEN INSERT (product_type, allowed_location, is_active) 
                           VALUES (src.pt, src.loc, 'Y');
                END IF;
            END IF;
            v_start := v_end + 1;
        END IF;
    END LOOP;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✅ Location config and locations table synced');
END;
/



-- ============================================
-- 8. ΕΠΑΛΗΘΕΥΣΗ
-- ============================================
SELECT * FROM products;
SELECT * FROM locations;
SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM orders;
SELECT * FROM order_items;
SELECT product_id FROM inventory;
SELECT * from VALID_PRODUCT_TYPES;
SELECT * from VALID_LOCATION_MAPPINGS;
SELECT user FROM dual;
SELECT check_stock('P001', 2) FROM dual;

SET SERVEROUTPUT ON;

BEGIN
  process_order_proc(1);
END;
/

UPDATE inventory
SET quantity_number = quantity_number - 1
WHERE product_id = 'P001';

COMMIT;
